import { Inter } from 'next/font/google'
import './globals.css'
import './chat.scss'
import { UserAuthContextProvider } from './context/userAuthContext'
import TanStackProvider from './context/reactQueryContext'
import { ChatContextProvider } from './context/chatContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" >
      <TanStackProvider>
      <UserAuthContextProvider>
      <ChatContextProvider>
      <body className={inter.className}>{children}</body>
      </ChatContextProvider>
      </UserAuthContextProvider>
      </TanStackProvider>
    </html>
  )
}
