import { Inter } from 'next/font/google'
import './globals.css'
import { UserAuthContextProvider } from './context/userAuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
       {/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
       <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@500;600;700&display=swap" rel="stylesheet"/> */}
      <UserAuthContextProvider>
      <body className={inter.className}>{children}</body>
      </UserAuthContextProvider>
    </html>
  )
}
